[project]
name = "gc-reservation-macro"
version = "0.1.0"
description = "Geumcheon Reservation Macro"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyinstaller>=6.16.0",
    "python-dotenv>=1.1.1",
    "selenium>=4.37.0",
    "webdriver-manager>=4.0.2",
]
